# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"html_vid": "00_lookatdata.ipynb",
         "html_titled_vid": "00_lookatdata.ipynb",
         "html_vids": "00_lookatdata.ipynb"}

modules = ["nb_00.py"]

doc_url = "https://qAp.github.io/kgl_deepfake/"

git_url = "https://github.com/qAp/kgl_deepfake/tree/master/"

def custom_doc_links(name): return None
