# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_JPG_Compression_Augmentation.ipynb (unless otherwise specified).

__all__ = ['jpgcompression']

# Cell
from torchvision import transforms

def _jpgcompression(x):
    quality = random.randrange(10, 100)
    x = transforms.ToPILImage()(x).convert("RGB")
    outputIoStream = BytesIO()
    x.save(outputIoStream, "JPEG", quality=quality, optimice=True)
    outputIoStream.seek(0)
    img = PIL.Image.open(outputIoStream)
    tensor = transforms.ToTensor()(img)
    return tensor

# Cell
jpgcompression = TfmPixel(_jpgcompression, order=10)