# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02bis_Create_Dataset-Copy1.ipynb (unless otherwise specified).

__all__ = []

# Cell
from .nb_01 import *
from fastai.vision import *
from .nb_00 import *
from IPython.display import HTML
import cv2
from tqdm import tqdm
from facenet_pytorch import MTCNN
import time