# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_lookatdata.ipynb (unless otherwise specified).

__all__ = ['html_vid', 'html_vid', 'html_titled_vid', 'html_vids']

# Cell
from fastai.vision import *

# Cell
from IPython.display import display, Video, HTML

# Cell
def html_vid(fname, **kwargs): return display(Video(fname, **kwargs))

# Cell
def html_vid(fname):
    "Return HTML for video."
    return f'''
    <video width="300" height="250" controls>
    <source src="{fname}" type="video/mp4">
    </video>
    '''

# Cell
def html_titled_vid(fname, title):
    "Return HTML for titled video."
    return f'<div><p>{title}</p><br>{html_vid(fname)}</div>'

# Cell
def html_vids(fnames, titles=None, ncols=3):
    "Return HTML for table of (titled) videos."
    n = len(fnames)
    if titles is None: titles = n * ['']
    assert len(titles) == n
    rs = []
    for i in range(0, n, ncols):
        fs, ts = fnames[i:i+ncols], titles[i:i+ncols]
        xs = (html_titled_vid(f, t) for f,t in zip(fs, ts))
        xs = (f'<td>{x}</td>' for x in xs)
        r = f"<tr>{''.join(xs)}</tr>"
        rs.append(r)
    return f"<table>{''.join(rs)}</table>"