#AUTOGENERATED! DO NOT EDIT! File to edit: dev/02bis_Create_Dataset.ipynb (unless otherwise specified).

__all__ = ['show_faces', 'plot_faces']

#Cell
from .nb_01 import *
from fastai.vision import *
from .nb_00 import *
from IPython.display import HTML
import cv2
from tqdm import tqdm
from facenet_pytorch import MTCNN
import time

#Cell
def show_faces(faces, idxs):
    ncols = 4
    nrows = int((len(idxs) - 1) / ncols) + 1
    _, axs = plt.subplots(ncols=ncols, nrows=nrows, figsize=(18, 4*nrows))
    for idx, ax in itertools.zip_longest(idxs, axs.flatten()):
        if idx:
            #img = np.array(faces[idx])
            ax.imshow(diff[idx].permute(1, 2, 0)/255.); ax.set_title(idx)
        ax.axis('off')

#Cell
def plot_faces(faces, idxs):
    ncols = 4
    nrows = int((len(idxs) - 1) / ncols) + 1
    _, axs = plt.subplots(ncols=ncols, nrows=nrows, figsize=(18, 4*nrows))
    for idx, ax in itertools.zip_longest(idxs, axs.flatten()):
        if idx:
            #img = np.array(faces[idx])
            ax.imshow(diff[idx].permute(1, 2, 0)/255.); ax.set_title(idx)
        ax.axis('off')